### ISSUE TITLE
Getting stuck at API call

### ISSUE THREAD

**Issue by hv-abacus** [rainym00d/LLM4RS#2]
Hi, running `python script/run.py`  is getting stuck (at `(pid, sts) = os.waitpid(self.pid, wait_flags)`) for me during the API request, specifically in the below section of `src/api/openai.py`:
```python
async with session.post(
    url=request_url, headers=request_header, json=self.request_json, proxy=proxy
) as response:
    response = await response.json()
```
I am using the below arguments.
```python
class MyArgs(Xp):
    model = ["text-davinci-003"]
    domain = ["Book"]
    task = ["list"]
    no_instruction = False
    example_num = [1]
    begin_index = 5
    end_index = 6
    api_key = "MY_API_KEY"
    max_requests_per_minute = 2000
    max_tokens_per_minute = 80000
    max_attempts = 100
    proxy = None
```

**Comment by rainym00d** [comment]
Thanks for your issue!

I believe that the most likely reason for this issue is a network problem. 

Since in this step, what we only to do is using the `post` method from `aiohttp` to send asynchronous requests. 

You could try changing your network environment or setting the `proxy` parameter to see if it resolves the issue.

On the other hand, you could try following command from [OpenAI website](https://platform.openai.com/docs/api-reference/chat/create) to check your network environment.

```shell
# curl

curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [{"role": "user", "content": "Hello!"}]
  }'
```

```python
# python

import os
import openai
openai.api_key = os.getenv("OPENAI_API_KEY")

completion = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "user", "content": "Hello!"}
  ]
)

print(completion.choices[0].message)
```

**Comment by hv-abacus** [comment]
Removing the `proxy` variable from the POST request in `src/api/openai.py` fixed it for me. Thanks!

**Comment by Ziyu0118** [comment]
@hv-abacus Can you tell me which line you modified? I removed the proxy variable where the code "async with session.post(
                    url=request_url, headers=request_header, json=self.request_json, proxy=proxy
                ) as response:" , but it still not work
